---
abstract: 'create extendable and reusable attributes '
author:
  - 'Christopher Brown <ctbrown@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.71'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Attribute
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.63
  Moose::Exporter: 0
  Moose::Util: 0
  Moose::Util::MetaRole: 0
  MooseX::AttributeHelpers: 0.13
version: 0.02
